name: Build and Run C Program

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile C program
      run: gcc -o meu_programa meu_programa.c

    - name: Run C program
      run: ./super_trunfo.C